version: '3.9'

services:
  front-end:
    build: ./front-end
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./front-end/nginx/nginx_soa.conf:/etc/nginx/conf.d/default.conf"
      - "./front-end/nginx/letsencrypt:/etc/letsencrypt"
    networks:
      - proxy-net
    depends_on:
      - auth
      - question-management
      - question-provider

  esb:
    build: ./esb

  auth:
    build: ./auth
    ports:
      - "3001"
    networks:
      - proxy-net

  question-management:
    build: ./question-management
    ports:
      - "3002"
    networks:
      - proxy-net

  question-provider:
    build: ./question-provider
    ports:
      - "3003"
    networks:
      - proxy-net

  data-layer:
    build: ./data-layer
    networks:
      - redis-net
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - "6379"
    volumes:
      - "./data-layer/data:/data"
    networks:
      - redis-net

networks:
  proxy-net:
  redis-net: